// Generated from seed_data.py. Static question bank for GitHub Pages.
export const QUESTIONS = [
  {
    "id": 1,
    "topic_num": 1,
    "question": "Segun la Constitucion Espanola de 1978, cual de los siguientes derechos fundamentales esta recogido en el Titulo I?",
    "option_a": "El derecho a la propiedad industrial exclusiva",
    "option_b": "El derecho a la vida y a la integridad fisica (art. 15)",
    "option_c": "El derecho a la jubilacion anticipada universal",
    "option_d": "El derecho a la libre competencia economica ilimitada",
    "correct": "B",
    "explanation": "El art. 15 CE reconoce el derecho a la vida y a la integridad fisica y moral, sin que en ningun caso pueda nadie ser sometido a torturas ni a penas o tratos inhumanos o degradantes."
  },
  {
    "id": 2,
    "topic_num": 1,
    "question": "Cuantos Titulos componen la estructura de la Constitucion Espanola de 1978?",
    "option_a": "8 Titulos",
    "option_b": "9 Titulos, mas Titulo Preliminar y Disposiciones",
    "option_c": "10 Titulos",
    "option_d": "7 Titulos y un Preliminar",
    "correct": "B",
    "explanation": "La CE de 1978 se estructura en Titulo Preliminar, 10 Titulos (I a X) y Disposiciones Adicionales, Transitorias, Derogatorias y Final."
  },
  {
    "id": 3,
    "topic_num": 2,
    "question": "Segun el Titulo IV de la CE, quien preside el Gobierno de la Nacion?",
    "option_a": "El Rey",
    "option_b": "El Presidente del Congreso de los Diputados",
    "option_c": "El Presidente del Gobierno",
    "option_d": "El Vicepresidente primero",
    "correct": "C",
    "explanation": "El art. 98 CE establece que el Gobierno esta compuesto por el Presidente, los Vicepresidentes, en su caso, los Ministros y los demas miembros que establezca la ley. Corresponde al Presidente del Gobierno la direccion de la politica interior y exterior."
  },
  {
    "id": 4,
    "topic_num": 2,
    "question": "El Titulo VIII de la Constitucion se refiere principalmente a:",
    "option_a": "La organizacion territorial del Estado",
    "option_b": "El poder judicial",
    "option_c": "Las Cortes Generales",
    "option_d": "La Corona",
    "correct": "A",
    "explanation": "El Titulo VIII (arts 143 a 158) regula la Organizacion Territorial del Estado, reconociendo la autonomia de las nacionalidades y regiones que integran Espana."
  },
  {
    "id": 5,
    "topic_num": 3,
    "question": "Segun la Ley 7/1985, de Bases del Regimen Local, cual es el organo de gobierno municipal?",
    "option_a": "El Pleno unicamente",
    "option_b": "La Alcaldia o Junta de Gobierno Local",
    "option_c": "El Secretario del Ayuntamiento",
    "option_d": "El Interventor",
    "correct": "B",
    "explanation": "El art. 21 LRBL establece que el gobierno y la administracion municipal corresponden a la Alcaldia, integrada por el Alcalde y los Tenientes de Alcalde, o a la Junta de Gobierno Local en municipios de poblacion superior a 5.000 habitantes."
  },
  {
    "id": 6,
    "topic_num": 3,
    "question": "En la organizacion provincial segun la Ley 7/1985, quien ejerce la presidencia de la Diputacion?",
    "option_a": "El Delegado del Gobierno",
    "option_b": "El Presidente elegido por los Diputados provinciales",
    "option_c": "El Alcalde del municipio de mayor poblacion",
    "option_d": "El Secretario Provincial",
    "correct": "B",
    "explanation": "El art. 31 LRBL establece que la Diputacion esta constituida por el Presidente, la Vicepresidencia, la Junta Provincial y los Diputados, siendo el Presidente elegido por los Diputados entre sus miembros."
  },
  {
    "id": 7,
    "topic_num": 4,
    "question": "El Real Decreto Legislativo 781/1986 aprueba el texto refundido de disposiciones legales vigentes en materia de:",
    "option_a": "Funcion Publica",
    "option_b": "Regimen Local",
    "option_c": "Contratos del Sector Publico",
    "option_d": "Procedimiento Administrativo",
    "correct": "B",
    "explanation": "El RDL 781/1986 aprueba el Texto Refundido de las disposiciones legales vigentes en materia de Regimen Local, recogiendo la LRBL y otras normas complementarias."
  },
  {
    "id": 8,
    "topic_num": 4,
    "question": "Segun el RD 2568/1986, a que organo corresponde la funcion de fiscalizacion interna en las Entidades Locales?",
    "option_a": "Al Pleno",
    "option_b": "A la Intervencion",
    "option_c": "Al Secretario",
    "option_d": "A la Junta de Gobierno",
    "correct": "B",
    "explanation": "La Intervencion General u organo de fiscalizacion interna ejerce el control interno de la gestion economico-financiera, segun el Titulo II del RD 2568/1986."
  },
  {
    "id": 9,
    "topic_num": 5,
    "question": "Segun la Ley 39/2015, que plazo maximo tienen las Administraciones Publicas para resolver y notificar los procedimientos administrativos?",
    "option_a": "1 mes",
    "option_b": "3 meses (art. 42.1 LPACAP)",
    "option_c": "6 meses",
    "option_d": "12 meses",
    "correct": "B",
    "explanation": "El art. 42.1 LPACAP establece que el plazo maximo para resolver y notificar es de 3 meses, salvo que una norma con rango de ley establezca otro plazo."
  },
  {
    "id": 10,
    "topic_num": 5,
    "question": "En la LPACAP, la capacidad de obrar de los menores de edad en el ambito administrativo se reconoce a partir de:",
    "option_a": "Los 14 anos",
    "option_b": "Los 16 anos",
    "option_c": "Los 18 anos",
    "option_d": "Los 12 anos",
    "correct": "B",
    "explanation": "El art. 3.3 LPACAP establece que tienen capacidad para ser parte e interesados en el procedimiento administrativo quienes hayan cumplido los dieciséis anos."
  },
  {
    "id": 11,
    "topic_num": 6,
    "question": "Segun la LPACAP, un acto administrativo vencido en su plazo de recurso y que no ha sido impugnado se denomina:",
    "option_a": "Acto nulo",
    "option_b": "Acto firme en via administrativa",
    "option_c": "Acto anulable",
    "option_d": "Acto provision",
    "correct": "B",
    "explanation": "El art. 51 LPACAP establece que la firmeza en via administrativa se produce cuando el acto no ha sido impugnado en el plazo establecido, o cuando se ha desestimado el recurso."
  },
  {
    "id": 12,
    "topic_num": 6,
    "question": "La nulidad de pleno derecho de los actos administrativos (art. 47 LPACAP) afecta a actos que:",
    "option_a": "Solo incurran en error de hecho",
    "option_b": "Vulneren la Constitucion, las leyes u otros derechos y libertades publicas",
    "option_c": "Carezcan de motivacion extendida",
    "option_d": "Hayan sido dictados fuera del horario de oficina",
    "correct": "B",
    "explanation": "El art. 47.1 LPACAP declara nulos de pleno derecho los actos que infrinjan la Constitucion, la ley o cualquier otra disposicion de rango legal, o lesionen derechos y libertades publicas."
  },
  {
    "id": 13,
    "topic_num": 7,
    "question": "Segun la Ley 31/1995 de Prevencion de Riesgos Laborales, los principios de la accion preventiva incluyen:",
    "option_a": "Evitar los riesgos, evaluar los que no se puedan evitar y combatirlos en su origen",
    "option_b": "Solo informar al trabajador de los riesgos existentes",
    "option_c": "Delegar la prevencion exclusivamente en las mutuas de accidentes",
    "option_d": "Realizar controles medicos anuales gratuitos unicamente",
    "correct": "A",
    "explanation": "El art. 15 LPRL establece principios preventivos: evitar riesgos, evaluar los inevitables, combatir en origen, adaptar trabajo a persona, tener en cuenta la evolucion de la tecnica, sustituir lo peligroso por lo seguro, planificar la prevencion, aplicar medidas coherentes y dar prioridad a protecciones colectivas."
  },
  {
    "id": 14,
    "topic_num": 7,
    "question": "La evaluacion de riesgos obligatoria segun la LPRL debe ser realizada por:",
    "option_a": "Solo el Servicio de Prevencion Ajeno",
    "option_b": "El empresario, que puede realizarla directamente o mediante servicios de prevencion",
    "option_c": "Exclusivamente la Inspeccion de Trabajo",
    "option_d": "El comite de empresa unicamente",
    "correct": "B",
    "explanation": "El art. 14 LPRL impone al empresario la obligacion de evaluar los riesgos, pudiendo realizarla directamente, mediante servicio de prevencion propio o ajeno."
  },
  {
    "id": 15,
    "topic_num": 8,
    "question": "La Ley Organica 3/2007, de igualdad efectiva de mujeres y hombres, establece que las Administraciones Publicas deben promover la igualdad mediante:",
    "option_a": "La prohibicion expresa de la contratacion femenina en ciertos sectores",
    "option_b": "La integracion del principio de igualdad en la planificacion presupuestaria y evaluacion de politicas publicas",
    "option_c": "La reduccion de la jornada laboral exclusiva para mujeres",
    "option_d": "La cuota de genero del 60% en todos los organos publicos",
    "correct": "B",
    "explanation": "El art. 15 LO 3/2007 establece la transversalidad de la igualdad en las politicas publicas, incluyendo la incorporacion del principio en la planificacion presupuestaria (presupuestos con perspectiva de genero)."
  },
  {
    "id": 16,
    "topic_num": 8,
    "question": "Segun la Ley 4/2018 de Castilla-La Mancha para una Sociedad Libre de Violencia de Genero, la violencia de genero se entiende como:",
    "option_a": "Cualquier altercado domestico ocasional",
    "option_b": "Cualquier acto de violencia fisica, psicologica o sexual contra una mujer por el mero hecho de serlo, o que afecte desproporcionadamente a mujeres",
    "option_c": "Solo los delitos de lesiones en el ambito familiar",
    "option_d": "La discriminacion laboral por razon de sexo",
    "correct": "B",
    "explanation": "El Art. 1 Ley 4/2018 CLM define la violencia de genero como cualquier acto de violencia fisica, psicologica o sexual contra las mujeres por el mero hecho de serlo, incluyendo todo tipo de violencia que afecte desproporcionadamente a mujeres."
  },
  {
    "id": 17,
    "topic_num": 9,
    "question": "Segun el Reglamento eIDAS, la firma electronica avanzada debe permitir:",
    "option_a": "La identificacion del signatario y detectar cualquier cambio posterior en los datos firmados",
    "option_b": "Solo la identificacion del documento firmado",
    "option_c": "La encriptacion completa del documento",
    "option_d": "La firma simultanea por varios signatarios sin identificacion",
    "correct": "A",
    "explanation": "El Reglamento eIDAS (UE) 910/2014 define la firma electronica avanzada como aquella que permite identificar al signatario y detectar cualquier cambio posterior de los datos firmados, vinculada de forma unica al signatario y bajo su control exclusivo."
  },
  {
    "id": 18,
    "topic_num": 9,
    "question": "La aplicacion de firma electronica @firma del MINHAP permite:",
    "option_a": "Verificar y validar firmas electronicas de cualquier tipo conforme al Esquema Nacional de Seguridad",
    "option_b": "Solo firmar documentos con certificados de la FNMT",
    "option_c": "Cifrar archivos usando AES-256 exclusivamente",
    "option_d": "Gestionar unicamente firmas PAdES en formato PDF",
    "correct": "A",
    "explanation": "@firma es la plataforma del MINHAP que proporciona servicios de firma y validacion de firmas electronicas, admitiendo multiples formatos (XAdES, CAdES, PAdES) y cumpliendo con el ENS."
  },
  {
    "id": 19,
    "topic_num": 10,
    "question": "En una Infraestructura de Clave Publica (PKI), que funcion cumple la Autoridad de Certificacion (CA)?",
    "option_a": "Almacenar los datos cifrados de los usuarios",
    "option_b": "Emitir, revocar y gestionar certificados digitales que vinculan una clave publica con la identidad de un sujeto",
    "option_c": "Generar claves privadas para todos los usuarios",
    "option_d": "Descifrar mensajes entre usuarios",
    "correct": "B",
    "explanation": "La CA es el elemento central de una PKI que actua como tercero de confianza, emitiendo certificados tras verificar la identidad del solicitante y manteniendo listas de revocacion (CRL)."
  },
  {
    "id": 20,
    "topic_num": 10,
    "question": "En el protocolo TLS (Transport Layer Security), que fase se encarga de acordar los parametros criptograficos entre cliente y servidor?",
    "option_a": "La fase de handshake",
    "option_b": "La fase de transferencia de datos",
    "option_c": "La fase de cierre de conexion",
    "option_d": "La fase de renegociacion",
    "correct": "A",
    "explanation": "El handshake TLS es el proceso inicial en el que cliente y servidor acuerdan la version del protocolo, suite criptografica, intercambian claves y autentican identidades mediante certificados."
  },
  {
    "id": 21,
    "topic_num": 11,
    "question": "El Esquema Nacional de Seguridad (Real Decreto 311/2022) clasifica los sistemas segun su criticidad en:",
    "option_a": "Solo dos niveles: basico y alto",
    "option_b": "Tres categorias: bajo, medio y alto, cada uno con un conjunto de medidas obligatorias",
    "option_c": "Cinco niveles numericos del 1 al 5",
    "option_d": "Ninguna clasificacion, todas las medidas son opcionales",
    "correct": "B",
    "explanation": "El ENS establece tres categorias (bajo, medio, alto) definiendo medidas de seguridad proporcionales a la criticidad. Cada categoria incluye medidas obligatorias del Esquema Nacional y de cada organismo."
  },
  {
    "id": 22,
    "topic_num": 11,
    "question": "Segun el ENS, los principios basicos de seguridad de la informacion incluyen:",
    "option_a": "Solo confidencialidad y disponibilidad",
    "option_b": "Confidencialidad, integridad, trazabilidad, autenticidad y disponibilidad",
    "option_c": "Velocidad, escalabilidad y redundancia",
    "option_d": "Usabilidad, accesibilidad y rendimiento",
    "correct": "B",
    "explanation": "El Anexo I del ENS establece los principios basicos: confidencialidad, integridad, trazabilidad, autenticidad y disponibilidad. Estos principios orientan la seleccion y aplicacion de medidas de seguridad."
  },
  {
    "id": 23,
    "topic_num": 12,
    "question": "Segun el RGPD, el responsable del tratamiento debe informar al interesado sobre el tratamiento de sus datos en el momento de:",
    "option_a": "Solo cuando el interesado lo solicite expresamente",
    "option_b": "La obtencion de los datos, con caracter previo (principio de transparencia, art. 13)",
    "option_c": "Un mes despues de la obtencion de los datos",
    "option_d": "Unicamente cuando haya una filtracion de seguridad",
    "correct": "B",
    "explanation": "El art. 12 y 13 RGPD establecen el deber de informacion cuando los datos se obtienen del interesado, proporcionandola de forma concisa, transparente, inteligible y facilmente accesible."
  },
  {
    "id": 24,
    "topic_num": 12,
    "question": "En materia de proteccion de datos, la LOPDGDD (Ley Organica 3/2018) desarrolla aspectos del RGPD relativos a:",
    "option_a": "La regulacion exclusiva de datos sanitarios",
    "option_b": "Derechos digitales, edad de consentimiento (14 anos), y regimen sancionador en Espana",
    "option_c": "Solo la creacion de la AEPD",
    "option_d": "La proteccion de datos de empresas unicamente",
    "correct": "B",
    "explanation": "La LOPDGDD desarrolla el RGPD en aspectos como: derechos digitales, edad de consentimiento (14 anos), tratamiento de datos de menores, representacion, deberes del delegado de proteccion de datos y regimen sancionador."
  },
  {
    "id": 25,
    "topic_num": 13,
    "question": "En la arquitectura de PostgreSQL, que proceso principal escucha conexiones entrantes y gestiona los backends?",
    "option_a": "El proceso WAL writer",
    "option_b": "El postmaster",
    "option_c": "El autovacuum launcher",
    "option_d": "El background writer",
    "correct": "B",
    "explanation": "El postmaster es el proceso principal del servidor PostgreSQL que escucha en el puerto configurado (por defecto 5432), acepta conexiones de clientes y genera un proceso backend dedicado para cada conexion."
  },
  {
    "id": 26,
    "topic_num": 13,
    "question": "Para garantizar la durabilidad (D de ACID), PostgreSQL utiliza principalmente:",
    "option_a": "Solo memoria compartida (shared_buffers)",
    "option_b": "Escritura previa de registro (WAL - Write Ahead Logging)",
    "option_c": "Solo indices B-tree",
    "option_d": "Tablas temporales en disco",
    "correct": "B",
    "explanation": "PostgreSQL utiliza WAL para garantizar durabilidad: antes de modificar los datos en disco, se escribe un registro en el WAL. Esto permite recuperar la base de datos tras un crash."
  },
  {
    "id": 27,
    "topic_num": 14,
    "question": "En PostgreSQL, cual es la jerarquia correcta de contencion de objetos?",
    "option_a": "Cluster > Base de datos > Esquema > Tabla",
    "option_b": "Base de datos > Cluster > Esquema > Tabla",
    "option_c": "Esquema > Base de datos > Tabla > Columna",
    "option_d": "Tabla > Esquema > Base de datos > Cluster",
    "correct": "A",
    "explanation": "La jerarquia en PostgreSQL es: Cluster (instancia del servidor) contiene multiples bases de datos. Cada base de datos contiene esquemas. Cada esquema contiene tablas, vistas, funciones, etc."
  },
  {
    "id": 28,
    "topic_num": 14,
    "question": "En PostgreSQL, que tipo de objeto permite ejecutar codigo procedural (PL/pgSQL) como parte del modelo relacional?",
    "option_a": "Solo las tablas",
    "option_b": "Las funciones (CREATE FUNCTION / CREATE OR REPLACE FUNCTION)",
    "option_c": "Los indices",
    "option_d": "Los tablespaces",
    "correct": "B",
    "explanation": "Las funciones en PostgreSQL permiten encapsular logica procedural usando PL/pgSQL u otros lenguajes. Se invocan directamente en consultas, triggers o procedimientos almacenados."
  },
  {
    "id": 29,
    "topic_num": 15,
    "question": "En PostgreSQL, el nivel de aislamiento por defecto de una transaccion es:",
    "option_a": "READ COMMITTED",
    "option_b": "REPEATABLE READ",
    "option_c": "SERIALIZABLE",
    "option_d": "READ UNCOMMITTED",
    "correct": "A",
    "explanation": "PostgreSQL utiliza READ COMMITTED como nivel de aislamiento por defecto. En este nivel, una consulta dentro de una transaccion solo ve datos confirmados antes de que la consulta comience."
  },
  {
    "id": 30,
    "topic_num": 15,
    "question": "Las propiedades ACID de una transaccion se refieren a:",
    "option_a": "Atomicidad, Consistencia, Aislamiento, Durabilidad",
    "option_b": "Accesibilidad, Concurrencia, Integridad, Disponibilidad",
    "option_c": "Autenticacion, Cifrado, Integridad, Depuracion",
    "option_d": "Asincronia, Cacheo, Indexacion, Distribucion",
    "correct": "A",
    "explanation": "ACID significa Atomicidad (todo o nada), Consistencia (el estado valido se mantiene), Aislamiento (transacciones concurrentes no se interfieren) y Durabilidad (los cambios persisten tras commit)."
  },
  {
    "id": 31,
    "topic_num": 16,
    "question": "Que herramienta de PostgreSQL se utiliza para realizar copias de seguridad logicas de una base de datos?",
    "option_a": "pg_ctl",
    "option_b": "pg_dump",
    "option_c": "psql",
    "option_d": "pg_waldump",
    "correct": "B",
    "explanation": "pg_dump es la herramienta estandar para realizar backups logicos. Genera un archivo SQL o en formato custom que puede restaurarse con pg_restore."
  },
  {
    "id": 32,
    "topic_num": 16,
    "question": "Para importar datos masivamente desde un archivo CSV en PostgreSQL, el metodo mas eficiente es:",
    "option_a": "INSERT INTO ... SELECT * FROM un archivo",
    "option_b": "La sentencia COPY o \\copy en psql",
    "option_c": "Crear una funcion PL/pgSQL que lea linea a linea",
    "option_d": "Usar pg_dump en modo restore",
    "correct": "B",
    "explanation": "COPY es la forma mas rapida de importar/exportar datos tabulares en PostgreSQL, ya que opera a nivel de servidor sin overhead de SQL parseado fila a fila."
  },
  {
    "id": 33,
    "topic_num": 17,
    "question": "En PostgreSQL, que comando se utiliza para obtener un plan de ejecucion detallado de una consulta incluyendo tiempos reales?",
    "option_a": "SHOW PLAN",
    "option_b": "EXPLAIN ANALYZE",
    "option_c": "DESCRIBE QUERY",
    "option_d": "PROFILE SQL",
    "correct": "B",
    "explanation": "EXPLAIN ANALYZE ejecuta la consulta y muestra el plan de ejecucion con tiempos y filas reales procesadas, siendo la herramienta fundamental para el tuning de rendimiento."
  },
  {
    "id": 34,
    "topic_num": 17,
    "question": "La operacion VACUUM en PostgreSQL se utiliza principalmente para:",
    "option_a": "Cifrar las tablas sensibles",
    "option_b": "Recuperar espacio de filas eliminadas o actualizadas y prevenir el swell de tablas",
    "option_c": "Compactar los indices automaticamente",
    "option_d": "Backup incremental de la base de datos",
    "correct": "B",
    "explanation": "PostgreSQL utiliza MVCC, por lo que las actualizaciones/eliminaciones dejan tuplas muertas. VACUUM marca estas tuplas como reutilizables. VACUUM FULL reescribe fisicamente las tablas para devolver espacio al SO."
  },
  {
    "id": 35,
    "topic_num": 18,
    "question": "En C#, que palabra clave se utiliza para declarar un tipo de valor que puede contener nulos?",
    "option_a": "object",
    "option_b": "nullable o el operador ? tras el tipo (int?)",
    "option_c": "var",
    "option_d": "dynamic",
    "correct": "B",
    "explanation": "Los tipos valor no aceptan null por defecto. Se usa Nullable<T> o la sintaxis T? (ej. int?) para permitir nulos en tipos de valor desde C# 2.0."
  },
  {
    "id": 36,
    "topic_num": 18,
    "question": "En C#, la diferencia fundamental entre una clase (class) y una estructura (struct) es que:",
    "option_a": "Las clases solo pueden tener metodos estaticos",
    "option_b": "Las clases son tipos referencia (almacenadas en heap) y las estructuras son tipos valor (almacenadas en stack)",
    "option_c": "Las estructuras no pueden tener constructores",
    "option_d": "Las clases solo existen en .NET Framework, no en .NET Core",
    "correct": "B",
    "explanation": "En C#, class define un tipo referencia (asignacion copia la referencia, no el objeto), mientras que struct define un tipo valor (asignacion copia el valor completo). Esto afecta rendimiento y semantica."
  },
  {
    "id": 37,
    "topic_num": 19,
    "question": "En ASP.NET Core MVC, que componente recibe las peticiones HTTP, ejecuta la logica de negocio y selecciona la vista a renderizar?",
    "option_a": "El Modelo",
    "option_b": "El Controller",
    "option_c": "La Vista",
    "option_d": "El Middleware",
    "correct": "B",
    "explanation": "El Controller es el componente C del patron MVC. Recibe peticiones, trabaja con los modelos y decide que vista presentar, pasandole los datos necesarios (ViewModel)."
  },
  {
    "id": 38,
    "topic_num": 19,
    "question": "Bootstrap es un framework CSS que proporciona principalmente:",
    "option_a": "Un motor de base de datos ligero",
    "option_b": "Un sistema de rejilla responsive, componentes de UI predefinidos y utilidades CSS",
    "option_c": "Un lenguaje de programacion para el frontend",
    "option_d": "Un servidor web embebido",
    "correct": "B",
    "explanation": "Bootstrap es un framework frontend que incluye un sistema de grid responsive basado en flexbox, componentes (navegacion, forms, tablas, modales) y utilidades de espaciado, colores y tipografia."
  },
  {
    "id": 39,
    "topic_num": 20,
    "question": "En Entity Framework Core, que clase principal actua como puente entre las entidades del dominio y la base de datos?",
    "option_a": "DbSet<T>",
    "option_b": "DbContext",
    "option_c": "IQueryable",
    "option_d": "SqlConnection",
    "correct": "B",
    "explanation": "DbContext es la clase central de EF Core que gestiona la conexion, el seguimiento de entidades (change tracking), las transacciones y la traduccion de consultas LINQ a SQL."
  },
  {
    "id": 40,
    "topic_num": 20,
    "question": "El comando `dotnet ef migrations add` en EF Core se utiliza para:",
    "option_a": "Compilar el proyecto",
    "option_b": "Crear un nuevo archivo de migracion basado en los cambios detectados en el modelo de datos",
    "option_c": "Conectar a la base de datos directamente",
    "option_d": "Eliminar todas las tablas existentes",
    "correct": "B",
    "explanation": "Las migraciones en EF Core permiten versionar el esquema de la base de datos. dotnet ef migrations add genera un archivo C# con las operaciones necesarias para actualizar el esquema (Up) o revertirlo (Down)."
  },
  {
    "id": 41,
    "topic_num": 21,
    "question": "En LINQ, el metodo de extension `Where` se utiliza para:",
    "option_a": "Ordenar elementos",
    "option_b": "Filtrar elementos segun una condicion booleana (predicado)",
    "option_c": "Agrupar elementos por una clave",
    "option_d": "Proyectar cada elemento en un nuevo tipo",
    "correct": "B",
    "explanation": "Where aplica un filtro a una secuencia, devolviendo solo los elementos que cumplen el predicado. Es el equivalente a la clausula WHERE de SQL."
  },
  {
    "id": 42,
    "topic_num": 21,
    "question": "Que metodo LINQ se utiliza para proyectar cada elemento de una coleccion a un nuevo tipo o forma?",
    "option_a": "Aggregate",
    "option_b": "Select",
    "option_c": "Join",
    "option_d": "GroupBy",
    "correct": "B",
    "explanation": "Select proyecta cada elemento a un nuevo tipo (o anonimo). Es equivalente a SELECT en SQL. Puede transformar propiedades, crear objetos anonimos o calcular valores derivados."
  },
  {
    "id": 43,
    "topic_num": 22,
    "question": "En ASP.NET Core MVC, el model binding es el proceso que:",
    "option_a": "Compila los modelos automaticamente desde la base de datos",
    "option_b": "Mapea datos de la peticion HTTP (formularios, query strings, JSON) a los parametros de accion del controlador o a las propiedades del modelo",
    "option_c": "Genera las vistas automaticamente para cada entidad",
    "option_d": "Cifra los datos de los modelos antes de enviarlos al cliente",
    "correct": "B",
    "explanation": "El model binding en ASP.NET Core convierte automaticamente los datos de la peticion (ruta, query, form, body, header) en objetos .NET que el controlador puede utilizar directamente."
  },
  {
    "id": 44,
    "topic_num": 22,
    "question": "En C# asincrono, la palabra clave `await` se utiliza para:",
    "option_a": "Detener permanentemente la ejecucion del programa",
    "option_b": "Suspender la ejecucion del metodo async hasta que la tarea completada sin bloquear el hilo",
    "option_c": "Eliminar automaticamente las excepciones",
    "option_d": "Forzar la ejecucion sincrona de un metodo",
    "correct": "B",
    "explanation": "await suspende la ejecucion del metodo async y devuelve el control al llamador sin bloquear el hilo. Cuando la tarea completa, la ejecucion continua desde el punto de suspension."
  },
  {
    "id": 45,
    "topic_num": 23,
    "question": "En ASP.NET Core, la diferencia entre autenticacion y autorizacion es que:",
    "option_a": "Son sinonimos y se usan indistintamente",
    "option_b": "La autenticacion identifica quien es el usuario; la autorizacion determina que puede hacer",
    "option_c": "La autenticacion controla el acceso a la base de datos; la autorizacion al frontend",
    "option_d": "La autenticacion usa solo cookies; la autorizacion solo tokens JWT",
    "correct": "B",
    "explanation": "Autenticacion = verificar la identidad del usuario (quien eres). Autorizacion = verificar permisos sobre recursos (que puedes hacer). Son procesos independientes pero secuenciales."
  },
  {
    "id": 46,
    "topic_num": 23,
    "question": "En ASP.NET Core MVC, los filtros de accion (Action Filters) se ejecutan:",
    "option_a": "Antes y despues de la ejecucion de un metodo de accion del controlador",
    "option_b": "Solo durante la fase de autorizacion",
    "option_c": "Unicamente al iniciar la aplicacion",
    "option_d": "Despues de que la vista ha sido renderizada",
    "correct": "A",
    "explanation": "Los Action Filters implementan IActionFilter, con OnActionExecuting (antes del metodo) y OnActionExecuted (despues). Permiten inyectar logica transversal como logging, validacion o transformacion de resultados."
  },
  {
    "id": 47,
    "topic_num": 24,
    "question": "Un controlador ASP.NET Core Web API habitualmente hereda de:",
    "option_a": "Controller",
    "option_b": "ControllerBase",
    "option_c": "ApiControllerBase",
    "option_d": "MvcController",
    "correct": "B",
    "explanation": "ControllerBase es la clase base para Web APIs (sin soporte de vistas). Controller hereda de ControllerBase y anade soporte para vistas Razor, siendo mas adecuado para MVC tradicional."
  },
  {
    "id": 48,
    "topic_num": 24,
    "question": "Segun las convenciones REST, que metodo HTTP se utiliza para actualizar parcialmente un recurso?",
    "option_a": "PUT",
    "option_b": "PATCH",
    "option_c": "POST",
    "option_d": "DELETE",
    "correct": "B",
    "explanation": "PATCH se usa para actualizaciones parciales (solo los campos enviados). PUT reemplaza el recurso completo. POST crea. DELETE elimina."
  },
  {
    "id": 49,
    "topic_num": 25,
    "question": "OData es un estandar de protocolo que permite:",
    "option_a": "Solo el envio de datos en formato CSV",
    "option_b": "Consultar y manipular datos mediante operaciones CRUD sobre URLs RESTful usando formato estandarizado",
    "option_c": "La encriptacion punto a punto de servicios web",
    "option_d": "La migracion automatica de bases de datos",
    "correct": "B",
    "explanation": "OData (Open Data Protocol) es un estandar OASIS que define practicas para crear y consumir APIs RESTful de forma uniforme, usando convenciones de URL para filtros, ordenacion, paginacion y CRUD."
  },
  {
    "id": 50,
    "topic_num": 25,
    "question": "En OData, para filtrar recursos donde el precio sea mayor que 100, se utiliza el parametro de consulta:",
    "option_a": "$sort=price gt 100",
    "option_b": "$filter=price gt 100",
    "option_c": "$search=price>100",
    "option_d": "$where=price gt 100",
    "correct": "B",
    "explanation": "La opcion de sistema $filter en OData permite expresar predicados de filtrado usando operadores como eq, ne, gt, ge, lt, le, and, or, not."
  },
  {
    "id": 51,
    "topic_num": 26,
    "question": "Blazor es un framework de .NET para construir interfaces web interactivas que permite ejecutar:",
    "option_a": "Solo codigo JavaScript en el navegador",
    "option_b": "Codigo C# tanto en el servidor como directamente en el navegador via WebAssembly",
    "option_c": "Solo aplicaciones de escritorio Windows",
    "option_d": "Solo APIs REST en el backend",
    "correct": "B",
    "explanation": "Blazor ofrece dos modelos de hosting: Blazor Server (UI en servidor, comunicacion via SignalR) y Blazor WebAssembly (UI ejecuta en navegador via WebAssembly, sin conexion persistente al servidor)."
  },
  {
    "id": 52,
    "topic_num": 26,
    "question": "La principal desventaja de Blazor Server frente a Blazor WebAssembly es que:",
    "option_a": "Requiere un plugin instalado en el navegador",
    "option_b": "Mantiene una conexion persistente (SignalR) con el servidor y es mas sensible a la latencia de red",
    "option_c": "No soporta componentes Razor",
    "option_d": "No puede ejecutar codigo C#",
    "correct": "B",
    "explanation": "Blazor Server renderiza en servidor y envia actualizaciones de DOM via SignalR. Si la conexion se interrumpe, la UI deja de responder. Ademas, cada interaccion genera latencia de ida y vuelta."
  },
  {
    "id": 53,
    "topic_num": 27,
    "question": "En Blazor, el binding unidireccional (one-way) se expresa con la sintaxis:",
    "option_a": "@bind-variable",
    "option_b": "@variable",
    "option_c": "{{variable}}",
    "option_d": "${variable}",
    "correct": "B",
    "explanation": "En Razor/Blazor, @variable renderiza el valor en la UI. El two-way binding usa @bind='variable' para sincronizar valor y evento de cambio."
  },
  {
    "id": 54,
    "topic_num": 27,
    "question": "En Blazor, los CascadingValue/CascadingParameter permiten:",
    "option_a": "Enviar datos desde un componente ancestro a todos sus descendientes sin pasar por parametros intermedios",
    "option_b": "Guardar datos en la base de datos local del navegador",
    "option_c": "Ejecutar codigo JavaScript desde C#",
    "option_d": "Crear web workers",
    "correct": "A",
    "explanation": "CascadingValue/CascadingParameter proporcionan un mecanismo de inyeccion de dependencias para el arbol de componentes, utiles para temas, configuracion o autenticacion compartida."
  },
  {
    "id": 55,
    "topic_num": 28,
    "question": "En Blazor, el ciclo de vida de un componente incluye metodos como OnInitialized, OnParametersSet y:",
    "option_a": "OnClick",
    "option_b": "OnAfterRender",
    "option_c": "OnSubmit",
    "option_d": "OnLoad",
    "correct": "B",
    "explanation": "OnAfterRender (y OnAfterRenderAsync) se invoca despues de que el componente ha renderizado en el DOM. Es util para operaciones que requieren acceso al DOM via JavaScript interop."
  },
  {
    "id": 56,
    "topic_num": 28,
    "question": "Para aislar CSS a un unico componente Blazor, se utiliza:",
    "option_a": "Un archivo style.css global",
    "option_b": "Un archivo .razor.css con el mismo nombre que el componente (CSS isolation)",
    "option_c": "La directiva @style en el componente",
    "option_d": "Un archivo SCSS compilado manualmente",
    "correct": "B",
    "explanation": "Blazor soporta CSS isolation: un archivo Component.razor.css se emite con un atributo de ambito unico, aplicando los estilos solo a ese componente. El framework lo gestiona automaticamente en tiempo de compilacion."
  },
  {
    "id": 57,
    "topic_num": 29,
    "question": "En Blazor, el componente `EditForm` se utiliza para:",
    "option_a": "Editar archivos de configuracion del servidor",
    "option_b": "Gestionar formularios de entrada de datos con soporte para validacion de modelo",
    "option_c": "Crear tablas de datos editables",
    "option_d": "Modificar el DOM directamente",
    "correct": "B",
    "explanation": "EditForm es el componente de formularios de Blazor. Se vincula a un modelo via Model='...' y soporta validacion mediante Data Annotations y componentes como DataAnnotationsValidator."
  },
  {
    "id": 58,
    "topic_num": 29,
    "question": "Para mostrar los mensajes de validacion de un campo especifico en Blazor, se utiliza el componente:",
    "option_a": "ValidationMessage<T>",
    "option_b": "ErrorList",
    "option_c": "FormFeedback",
    "option_d": "FieldError",
    "correct": "A",
    "explanation": "ValidationMessage<TValue> renderiza los mensajes de error asociados a una expresion de campo (For='@(() => model.Property)'). Se combina con DataAnnotationsValidator para mostrar errores de Data Annotations."
  },
  {
    "id": 59,
    "topic_num": 30,
    "question": "En Blazor, para solicitar un servicio registrado en el contenedor de DI dentro de un componente, se utiliza el atributo:",
    "option_a": "@using",
    "option_b": "@inject",
    "option_c": "@service",
    "option_d": "@import",
    "correct": "B",
    "explanation": "@inject Tipo Nombre inyecta un servicio desde el contenedor de dependencias (IServiceProvider) en el componente. Se registra services.AddSingleton/Scoped/Transient en Program.cs."
  },
  {
    "id": 60,
    "topic_num": 30,
    "question": "En ASP.NET Core/Blazor, el ciclo de vida Scoped de un servicio significa que:",
    "option_a": "Se crea una unica instancia para toda la aplicacion",
    "option_b": "Se crea una instancia nueva por cada peticion HTTP (en server) o cada sesion de componente (en WASM con HttpClient)",
    "option_c": "Se crea en cada constructor que lo solicite",
    "option_d": "Se destruye inmediatamente despues de usarlo",
    "correct": "B",
    "explanation": "Scoped crea una instancia por ambito. En Blazor Server coincide con el circuito. En Web APIs ASP.NET Core coincide con la peticion HTTP. No debe usarse para estado compartido entre usuarios (eso es Singleton)."
  },
  {
    "id": 61,
    "topic_num": 31,
    "question": "En Blazor WebAssembly, una forma comun de gestionar estado global compartido entre componentes es:",
    "option_a": "Usar variables estaticas en todos los componentes",
    "option_b": "Crear un servicio inyectado como Singleton que almacene el estado centralizado",
    "option_c": "Guardar todo en localStorage y leerlo en cada renderizado",
    "option_d": "Usar ViewState como en Web Forms",
    "correct": "B",
    "explanation": "Un servicio Singleton (ej. AppState o CartState) inyectado en @inject permite compartir estado entre componentes sin pasar parametros manualmente. Los eventos o StateHasChanged() notifican cambios."
  },
  {
    "id": 62,
    "topic_num": 31,
    "question": "En Blazor, para notificar a un componente que debe re-renderizarse tras un cambio de estado, se invoca:",
    "option_a": "Render()",
    "option_b": "StateHasChanged()",
    "option_c": "Update()",
    "option_d": "Refresh()",
    "correct": "B",
    "explanation": "StateHasChanged() marca el componente como requiriendo renderizado. El framework lo procesara en el siguiente ciclo de renderizado. Es util en escenarios async o eventos externos."
  },
  {
    "id": 63,
    "topic_num": 32,
    "question": "En Blazor, el componente `NavLink` se diferencia de una etiqueta `a` HTML estandar en que:",
    "option_a": "NavLink solo funciona en Blazor Server",
    "option_b": "NavLink detecta automaticamente la ruta activa y aplica clases CSS de activo",
    "option_c": "NavLink abre enlaces en una nueva pestana siempre",
    "option_d": "NavLink requiere autenticacion obligatoria",
    "correct": "B",
    "explanation": "NavLink renderiza un enlace y anade la clase 'active' (configurable) cuando la URL actual coincide con el href del enlace, mejorando la navegacion con indicadores visuales."
  },
  {
    "id": 64,
    "topic_num": 32,
    "question": "En Blazor, para navegar programaticamente a otra ruta desde codigo C#, se utiliza:",
    "option_a": "window.location.href",
    "option_b": "NavigationManager con el metodo NavigateTo()",
    "option_c": "Router.Navigate()",
    "option_d": "HttpClient.Get()",
    "correct": "B",
    "explanation": "NavigationManager es un servicio inyectado que proporciona metodos como NavigateTo(string uri) para navegacion programatica, y propiedades como Uri y BaseUri."
  },
  {
    "id": 65,
    "topic_num": 33,
    "question": "En Git, que comando se utiliza para configurar el nombre de usuario de forma global?",
    "option_a": "git config user.name \"Nombre\"",
    "option_b": "git config --global user.name \"Nombre\"",
    "option_c": "git set user \"Nombre\"",
    "option_d": "git user --set \"Nombre\"",
    "correct": "B",
    "explanation": "git config --global user.name establece el nombre de usuario a nivel global (archivo ~/.gitconfig). Sin --global se aplica solo al repositorio actual."
  },
  {
    "id": 66,
    "topic_num": 33,
    "question": "En Git, despues de modificar archivos, para prepararlos para el siguiente commit se utiliza:",
    "option_a": "git commit directamente",
    "option_b": "git add <archivo> o git add .",
    "option_c": "git push",
    "option_d": "git stage --all sin comando previo",
    "correct": "B",
    "explanation": "git add mueve los cambios al staging area (indice). Solo los cambios en staging se incluyen en el siguiente commit. git add . anade todos los cambios del directorio actual."
  },
  {
    "id": 67,
    "topic_num": 34,
    "question": "La diferencia principal entre `git merge` y `git rebase` al integrar cambios de una rama es que:",
    "option_a": "Ambos hacen exactamente lo mismo",
    "option_b": "Merge crea un commit de fusion conservando la historia; rebase reescribe los commits propios sobre la punta de la otra rama, creando una historia lineal",
    "option_c": "Rebase elimina todos los commits de la rama origen",
    "option_d": "Merge solo funciona con ramas locales",
    "correct": "B",
    "explanation": "Merge conserva la historia bifurcada con un commit de merge. Rebase mueve los commits de la rama actual al final de la rama destino, reescribiendo hashes pero generando historial lineal."
  },
  {
    "id": 68,
    "topic_num": 34,
    "question": "En Git, `git stash` se utiliza para:",
    "option_a": "Eliminar permanentemente cambios no confirmados",
    "option_b": "Guardar temporalmente cambios no confirmados en una pila para recuperarlos despues",
    "option_c": "Fusionar dos ramas rapidamente",
    "option_d": "Publicar cambios en el repositorio remoto",
    "correct": "B",
    "explanation": "git stash guarda el estado del working directory e index en una pila (stash stack), limpiando el working directory. Se recupera con git stash pop o git stash apply."
  },
  {
    "id": 69,
    "topic_num": 35,
    "question": "En Git, el flujo de trabajo GitFlow define principalmente las ramas:",
    "option_a": "Solo main y develop",
    "option_b": "main/master, develop, feature/*, release/*, hotfix/* y support/*",
    "option_c": "Solo ramas de integracion continua",
    "option_d": "Una rama unica compartida por todo el equipo",
    "correct": "B",
    "explanation": "GitFlow (Vincent Driessen) define: main (produccion), develop (integracion), feature/* (nuevas funcionalidades), release/* (preparacion de version), hotfix/* (correcciones urgentes en produccion)."
  },
  {
    "id": 70,
    "topic_num": 35,
    "question": "El comando `git fetch` se diferencia de `git pull` en que:",
    "option_a": "Son exactamente iguales",
    "option_b": "fetch descarga cambios del remoto sin fusionarlos; pull hace fetch + merge automaticamente",
    "option_c": "fetch solo funciona con HTTPS",
    "option_d": "pull solo descarga metadatos sin codigo",
    "correct": "B",
    "explanation": "git fetch actualiza las referencias remotas (origin/main) sin modificar la rama local. git pull = git fetch + git merge, lo que actualiza directamente la rama actual."
  },
  {
    "id": 71,
    "topic_num": 36,
    "question": "La plataforma SedipuAlb@ es la sede electronica de:",
    "option_a": "La Junta de Comunidades de Castilla-La Mancha",
    "option_b": "La Diputacion Provincial de Albacete",
    "option_c": "El Ayuntamiento de Albacete",
    "option_d": "La Delegacion del Gobierno en Albacete",
    "correct": "B",
    "explanation": "SedipuAlb@ es la plataforma de Administracion Electronica de la Diputacion Provincial de Albacete, que agrupa sus servicios de sede electronica y tramitacion."
  },
  {
    "id": 72,
    "topic_num": 36,
    "question": "Segun la Ley 39/2015, una sede electronica es:",
    "option_a": "Una pagina web informativa sobre la Administracion",
    "option_b": "El punto de acceso electronico a traves del cual una Administracion Publica comunica a los interesados los actos y actuaciones disponibles via telematica",
    "option_c": "Un centro fisico de atencion al ciudadano",
    "option_d": "Un servidor FTP de descarga de documentos",
    "correct": "B",
    "explanation": "El art. 2.h) LPACAP define sede electronica como el punto de acceso electronico a traves del cual los interesados acceden a la informacion, servicios y tramites de la Administracion."
  },
  {
    "id": 73,
    "topic_num": 37,
    "question": "El modulo SEFACE de SedipuAlb@ se utiliza para:",
    "option_a": "La gestion del registro electronico",
    "option_b": "La firma electronica y el sellado de tiempo",
    "option_c": "La facturacion electronica",
    "option_d": "La gestion de expedientes",
    "correct": "B",
    "explanation": "SEFACE (Servicio de Firma y Certificacion Electronica) gestiona la firma electronica, sellado de tiempo y validacion de firmas dentro de la plataforma SedipuAlb@."
  },
  {
    "id": 74,
    "topic_num": 37,
    "question": "El modulo SEGEX de SedipuAlb@ esta relacionado con:",
    "option_a": "La generacion de informes estadisticos",
    "option_b": "La gestion de la sede electronica y publicacion de informacion institucional",
    "option_c": "La interoperabilidad con otras administraciones",
    "option_d": "La gestion de recursos humanos",
    "correct": "B",
    "explanation": "SEGEX (Sede Electronica y Gestion de Expedientes Externos) gestiona la publicacion de informacion en la sede electronica y la atencion a tramites iniciados por ciudadanos."
  },
  {
    "id": 75,
    "topic_num": 38,
    "question": "La Red SARA (Sistema de Aplicaciones y Redes para las Administraciones) es:",
    "option_a": "Una red social para funcionarios publicos",
    "option_b": "La red de comunicaciones de las Administraciones Publicas espanolas que garantiza la interoperabilidad y seguridad",
    "option_c": "Un buscador universal de tramites administrativos",
    "option_d": "Un protocolo de transferencia de archivos FTP seguro",
    "correct": "B",
    "explanation": "La Red SARA es la red corporativa de comunicaciones del sector publico estatal, gestionada por el Ministerio de Asuntos Economicos y Transformacion Digital, que conecta las AAPP para el intercambio seguro de informacion."
  },
  {
    "id": 76,
    "topic_num": 38,
    "question": "El Protocolo SCSP (Sistema de Comunicaciones Seguras entre las Administraciones Publicas) permite:",
    "option_a": "Solo el envio de correos electronicos cifrados",
    "option_b": "El intercambio de datos y la verificacion de identidades entre administraciones de forma estandarizada y segura",
    "option_c": "La videoconferencia entre oficinas de registro",
    "option_d": "La impresion remota de documentos administrativos",
    "correct": "B",
    "explanation": "SCSP define especificaciones para el intercambio seguro de datos entre AAPP, incluyendo protocolos de verificacion de datos de identidad, residencia, etc., sobre la Red SARA."
  },
  {
    "id": 77,
    "topic_num": 39,
    "question": "Cl@ve es un sistema del Gobierno de Espana que proporciona:",
    "option_a": "Un almacenamiento en nube para documentos administrativos",
    "option_b": "Identificacion y autenticacion electronica de ciudadanos mediante distintos niveles de seguridad (Cl@ve Permanente, Cl@ve PIN, certificado)",
    "option_c": "Un buscador de empleo publico",
    "option_d": "Una plataforma de firma masiva de contratos publicos",
    "correct": "B",
    "explanation": "Cl@ve es el sistema electronico de identificacion y firma del Gobierno de Espana. Nivel basico con usuario/contrasena + SMS (Cl@ve PIN), nivel avanzado con certificado o DNIe (Cl@ve Permanente)."
  },
  {
    "id": 78,
    "topic_num": 39,
    "question": "La Carpeta Ciudadana del ciudadano permite principalmente:",
    "option_a": "Guardar documentos personales en la nube privada",
    "option_b": "Consultar notificaciones, comunicaciones, expedientes y actuaciones administrativas en las distintas administraciones publicas",
    "option_c": "Solicitar prestamos publicos",
    "option_d": "Gestionar la nomina de empleados publicos",
    "correct": "B",
    "explanation": "La Carpeta Ciudadana (carpeta Ciudadana del Punto de Acceso General) es un espacio personal donde los ciudadanos pueden consultar sus tramites, notificaciones y relaciones con todas las AAPP."
  },
  {
    "id": 79,
    "topic_num": 40,
    "question": "El nivel de conformidad AA de las WCAG 2.1 requiere:",
    "option_a": "Solo los criterios de nivel A",
    "option_b": "Todos los criterios de nivel A mas criterios adicionales de nivel AA",
    "option_c": "Solo criterios de nivel AAA",
    "option_d": "Ningun criterio especifico, solo recomendaciones",
    "correct": "B",
    "explanation": "WCAG define tres niveles: A (minimo), AA (nivel medio, requerido por la normativa europea), AAA (maximo). AA incluye todos los criterios A mas criterios adicionales como contraste de color mejorado."
  },
  {
    "id": 80,
    "topic_num": 40,
    "question": "Segun la Directiva (UE) 2016/2102 y la norma UNE-EN 301549, las paginas web de las Administraciones Publicas deben ser:",
    "option_a": "Accesibles solo desde navegadores Microsoft Edge",
    "option_b": "Accesibles para personas con discapacidad, cumpliendo niveles de conformidad WCAG 2.1 AA",
    "option_c": "Desarrolladas unicamente en HTML4",
    "option_d": "Sin contenido multimedia para facilitar la navegacion",
    "correct": "B",
    "explanation": "La Directiva 2016/2102 exige que los sitios web y apps moviles de las AAPP sean accesibles, conformes con la norma UNE-EN 301549 (que incorpora WCAG 2.1 nivel AA) y publiquen declaraciones de accesibilidad."
  },
  {
    "id": 81,
    "topic_num": 1,
    "question": "Que parte de la Constitucion Espanola de 1978 recoge los valores superiores del ordenamiento juridico?",
    "option_a": "Titulo VIII",
    "option_b": "Disposicion derogatoria",
    "option_c": "Titulo Preliminar",
    "option_d": "Titulo IV",
    "correct": "C",
    "explanation": "El Titulo Preliminar recoge, entre otros aspectos, los valores superiores, la soberania nacional y la forma politica del Estado."
  },
  {
    "id": 82,
    "topic_num": 1,
    "question": "Que institucion ejerce la potestad legislativa del Estado segun la Constitucion?",
    "option_a": "Defensor del Pueblo",
    "option_b": "Cortes Generales",
    "option_c": "Consejo de Estado",
    "option_d": "Tribunal Constitucional",
    "correct": "B",
    "explanation": "Las Cortes Generales representan al pueblo espanol y ejercen la potestad legislativa del Estado."
  },
  {
    "id": 83,
    "topic_num": 2,
    "question": "Que titulo constitucional regula el Gobierno y la Administracion?",
    "option_a": "Titulo X",
    "option_b": "Titulo IV",
    "option_c": "Titulo I",
    "option_d": "Titulo III",
    "correct": "B",
    "explanation": "El Titulo IV de la Constitucion regula el Gobierno y la Administracion."
  },
  {
    "id": 84,
    "topic_num": 2,
    "question": "Que titulo constitucional trata la organizacion territorial del Estado?",
    "option_a": "Titulo VIII",
    "option_b": "Titulo II",
    "option_c": "Titulo V",
    "option_d": "Titulo IX",
    "correct": "A",
    "explanation": "El Titulo VIII regula municipios, provincias y comunidades autonomas."
  },
  {
    "id": 85,
    "topic_num": 3,
    "question": "Segun la Ley 7/1985, que entidad local basica tiene personalidad juridica y plena capacidad para el cumplimiento de sus fines?",
    "option_a": "Municipio",
    "option_b": "Comarca",
    "option_c": "Mancomunidad",
    "option_d": "Area metropolitana",
    "correct": "A",
    "explanation": "El municipio es la entidad local basica de la organizacion territorial del Estado."
  },
  {
    "id": 86,
    "topic_num": 3,
    "question": "En la organizacion municipal comun, que organo preside la corporacion?",
    "option_a": "Interventor",
    "option_b": "Secretario",
    "option_c": "Tesorero",
    "option_d": "Alcalde",
    "correct": "D",
    "explanation": "El alcalde preside la corporacion municipal y dirige el gobierno y la administracion municipal."
  },
  {
    "id": 87,
    "topic_num": 4,
    "question": "Que norma aprueba el texto refundido de las disposiciones legales vigentes en materia de regimen local?",
    "option_a": "Ley Organica 3/2018",
    "option_b": "Real Decreto 203/2021",
    "option_c": "Ley 40/2015",
    "option_d": "Real Decreto Legislativo 781/1986",
    "correct": "D",
    "explanation": "El Real Decreto Legislativo 781/1986 aprueba el texto refundido de regimen local."
  },
  {
    "id": 88,
    "topic_num": 4,
    "question": "Que reglamento regula la organizacion, funcionamiento y regimen juridico de las entidades locales?",
    "option_a": "RGPD",
    "option_b": "TREBEP",
    "option_c": "ROF",
    "option_d": "ENS",
    "correct": "C",
    "explanation": "El ROF es el Reglamento de Organizacion, Funcionamiento y Regimen Juridico de las Entidades Locales."
  },
  {
    "id": 89,
    "topic_num": 5,
    "question": "En la Ley 39/2015, como se denomina quien promueve un procedimiento administrativo como titular de derechos o intereses legitimos?",
    "option_a": "Fedatario",
    "option_b": "Encargado del tratamiento",
    "option_c": "Interesado",
    "option_d": "Contratista",
    "correct": "C",
    "explanation": "La Ley 39/2015 define quienes tienen la condicion de interesados en el procedimiento administrativo."
  },
  {
    "id": 90,
    "topic_num": 5,
    "question": "Que permite acreditar que una persona actua en nombre de otra ante la Administracion?",
    "option_a": "Publicacion",
    "option_b": "Representacion",
    "option_c": "Recusacion",
    "option_d": "Convalidacion",
    "correct": "B",
    "explanation": "La representacion permite actuar ante las Administraciones Publicas por medio de otra persona."
  },
  {
    "id": 91,
    "topic_num": 6,
    "question": "Que vicio afecta a un acto administrativo que lesiona derechos fundamentales?",
    "option_a": "Prescripcion",
    "option_b": "Nulidad de pleno derecho",
    "option_c": "Anulabilidad leve",
    "option_d": "Caducidad",
    "correct": "B",
    "explanation": "Los actos que lesionan derechos y libertades susceptibles de amparo constitucional son nulos de pleno derecho."
  },
  {
    "id": 92,
    "topic_num": 6,
    "question": "Que requisito exige que el acto administrativo exponga las razones juridicas y facticas de su decision?",
    "option_a": "Motivacion",
    "option_b": "Notificacion por edictos",
    "option_c": "Archivo",
    "option_d": "Desistimiento",
    "correct": "A",
    "explanation": "La motivacion explica los hechos y fundamentos de derecho que justifican el acto."
  },
  {
    "id": 93,
    "topic_num": 7,
    "question": "En prevencion de riesgos laborales, que principio exige combatir los riesgos en su origen?",
    "option_a": "Principio de accion preventiva",
    "option_b": "Principio de caja unica",
    "option_c": "Principio de publicidad registral",
    "option_d": "Principio de devengo",
    "correct": "A",
    "explanation": "La accion preventiva incluye evitar riesgos, evaluarlos y combatirlos en su origen."
  },
  {
    "id": 94,
    "topic_num": 7,
    "question": "Que derecho tiene el trabajador frente a los riesgos laborales?",
    "option_a": "Libre eleccion de proveedor",
    "option_b": "Secreto profesional absoluto",
    "option_c": "Exencion de formacion",
    "option_d": "Proteccion eficaz en seguridad y salud",
    "correct": "D",
    "explanation": "La Ley 31/1995 reconoce el derecho a una proteccion eficaz en materia de seguridad y salud en el trabajo."
  },
  {
    "id": 95,
    "topic_num": 8,
    "question": "Que ley estatal regula la igualdad efectiva de mujeres y hombres?",
    "option_a": "Ley 7/1985",
    "option_b": "Ley 31/1995",
    "option_c": "Ley 9/2017",
    "option_d": "Ley Organica 3/2007",
    "correct": "D",
    "explanation": "La Ley Organica 3/2007 regula la igualdad efectiva de mujeres y hombres."
  },
  {
    "id": 96,
    "topic_num": 8,
    "question": "Que tipo de discriminacion se produce cuando una medida aparentemente neutra perjudica especialmente a personas de un sexo?",
    "option_a": "Recusacion",
    "option_b": "Silencio administrativo",
    "option_c": "Discriminacion indirecta",
    "option_d": "Discriminacion positiva prohibida",
    "correct": "C",
    "explanation": "La discriminacion indirecta deriva de disposiciones, criterios o practicas aparentemente neutros con efecto desfavorable."
  },
  {
    "id": 97,
    "topic_num": 9,
    "question": "Que aplicacion se utiliza habitualmente en la Administracion espanola para firmar electronicamente desde el navegador o escritorio?",
    "option_a": "Bootstrap",
    "option_b": "Git stash",
    "option_c": "AutoFirma",
    "option_d": "pg_restore",
    "correct": "C",
    "explanation": "AutoFirma permite realizar firmas electronicas con certificados digitales en equipos de usuario."
  },
  {
    "id": 98,
    "topic_num": 9,
    "question": "Que elemento vincula unos datos de verificacion de firma a un firmante y confirma su identidad?",
    "option_a": "RenderFragment",
    "option_b": "Certificado digital",
    "option_c": "Indice SQL",
    "option_d": "Controlador MVC",
    "correct": "B",
    "explanation": "El certificado digital asocia la identidad del titular con sus claves criptograficas."
  },
  {
    "id": 99,
    "topic_num": 10,
    "question": "Que infraestructura gestiona certificados digitales, autoridades de certificacion y revocacion?",
    "option_a": "OData",
    "option_b": "PKI",
    "option_c": "LINQ",
    "option_d": "SCSP",
    "correct": "B",
    "explanation": "Una PKI organiza certificados, autoridades de certificacion, registro y mecanismos de revocacion."
  },
  {
    "id": 100,
    "topic_num": 10,
    "question": "Que protocolo protege comunicaciones web mediante cifrado sobre HTTP?",
    "option_a": "TLS",
    "option_b": "PGP",
    "option_c": "SIR",
    "option_d": "MVC",
    "correct": "A",
    "explanation": "HTTPS utiliza TLS para autenticar el servidor y cifrar la comunicacion."
  },
  {
    "id": 101,
    "topic_num": 11,
    "question": "Que norma establece la politica de seguridad para la utilizacion de medios electronicos en el sector publico espanol?",
    "option_a": "Esquema Nacional de Seguridad",
    "option_b": "Bootstrap",
    "option_c": "Entity Framework Core",
    "option_d": "WCAG",
    "correct": "A",
    "explanation": "El ENS fija principios, requisitos y medidas de seguridad para sistemas del sector publico."
  },
  {
    "id": 102,
    "topic_num": 11,
    "question": "En el ENS, que determina la intensidad de las medidas de seguridad aplicables a un sistema?",
    "option_a": "Color corporativo",
    "option_b": "Numero de usuarios anonimos",
    "option_c": "Tipo de navegador",
    "option_d": "Categoria del sistema",
    "correct": "D",
    "explanation": "La categoria del sistema condiciona las medidas de seguridad que deben aplicarse."
  },
  {
    "id": 103,
    "topic_num": 12,
    "question": "Que reglamento europeo regula la proteccion de datos personales y su libre circulacion?",
    "option_a": "ROF",
    "option_b": "ENS",
    "option_c": "PGP",
    "option_d": "RGPD",
    "correct": "D",
    "explanation": "El Reglamento (UE) 2016/679 es el Reglamento General de Proteccion de Datos."
  },
  {
    "id": 104,
    "topic_num": 12,
    "question": "Que principio exige tratar solo los datos personales adecuados, pertinentes y limitados a lo necesario?",
    "option_a": "Rebase",
    "option_b": "Polimorfismo",
    "option_c": "Minimizacion de datos",
    "option_d": "Devengo",
    "correct": "C",
    "explanation": "La minimizacion limita los datos tratados a los necesarios para la finalidad perseguida."
  },
  {
    "id": 105,
    "topic_num": 13,
    "question": "En PostgreSQL, como se denomina el conjunto de bases de datos gestionadas por una misma instancia?",
    "option_a": "Valor en cascada",
    "option_b": "Sede electronica",
    "option_c": "Cluster de bases de datos",
    "option_d": "Pull request",
    "correct": "C",
    "explanation": "Un cluster PostgreSQL es el conjunto de bases de datos de una instancia del servidor."
  },
  {
    "id": 106,
    "topic_num": 13,
    "question": "Que proceso de PostgreSQL acepta conexiones de clientes y crea procesos de servidor?",
    "option_a": "NavigationManager",
    "option_b": "Postmaster",
    "option_c": "Kestrel",
    "option_d": "AutoFirma",
    "correct": "B",
    "explanation": "El proceso principal de PostgreSQL escucha conexiones y coordina procesos del servidor."
  },
  {
    "id": 107,
    "topic_num": 14,
    "question": "En PostgreSQL, que objeto agrupa tablas, vistas y funciones dentro de una base de datos?",
    "option_a": "Componente Razor",
    "option_b": "Esquema",
    "option_c": "Commit",
    "option_d": "Claim",
    "correct": "B",
    "explanation": "Los esquemas organizan objetos dentro de una base de datos PostgreSQL."
  },
  {
    "id": 108,
    "topic_num": 14,
    "question": "Que mecanismo de PostgreSQL permite controlar privilegios de usuarios y grupos?",
    "option_a": "Roles",
    "option_b": "Filtros MVC",
    "option_c": "WCAG",
    "option_d": "Ramas",
    "correct": "A",
    "explanation": "PostgreSQL usa roles para usuarios, grupos y asignacion de permisos."
  },
  {
    "id": 109,
    "topic_num": 15,
    "question": "Que instruccion confirma definitivamente una transaccion en PostgreSQL?",
    "option_a": "COMMIT",
    "option_b": "ROLLBACK",
    "option_c": "EXPLAIN",
    "option_d": "STASH",
    "correct": "A",
    "explanation": "COMMIT confirma los cambios realizados en una transaccion."
  },
  {
    "id": 110,
    "topic_num": 15,
    "question": "Que propiedad ACID garantiza que una transaccion se ejecuta completa o no se aplica?",
    "option_a": "Cascada",
    "option_b": "Enrutado",
    "option_c": "Accesibilidad",
    "option_d": "Atomicidad",
    "correct": "D",
    "explanation": "La atomicidad evita estados parciales: la transaccion se completa entera o se deshace."
  },
  {
    "id": 111,
    "topic_num": 16,
    "question": "Que herramienta de PostgreSQL genera copias de seguridad logicas de una base de datos?",
    "option_a": "psql",
    "option_b": "pg_restore",
    "option_c": "AutoFirma",
    "option_d": "pg_dump",
    "correct": "D",
    "explanation": "pg_dump exporta una base de datos PostgreSQL en formatos logicos de copia."
  },
  {
    "id": 112,
    "topic_num": 16,
    "question": "Que comando de PostgreSQL se usa para restaurar copias en formato personalizado o directorio?",
    "option_a": "git rebase",
    "option_b": "dotnet run",
    "option_c": "pg_restore",
    "option_d": "pg_dump",
    "correct": "C",
    "explanation": "pg_restore restaura copias creadas por pg_dump en formatos no planos."
  },
  {
    "id": 113,
    "topic_num": 17,
    "question": "Que sentencia de PostgreSQL muestra el plan de ejecucion de una consulta?",
    "option_a": "SELECT DISTINCT",
    "option_b": "MERGE",
    "option_c": "EXPLAIN",
    "option_d": "COMMIT",
    "correct": "C",
    "explanation": "EXPLAIN permite analizar como PostgreSQL ejecutara una consulta."
  },
  {
    "id": 114,
    "topic_num": 17,
    "question": "Que estructura acelera busquedas a cambio de espacio y coste de mantenimiento?",
    "option_a": "Sede",
    "option_b": "Indice",
    "option_c": "RenderFragment",
    "option_d": "Certificado",
    "correct": "B",
    "explanation": "Los indices mejoran consultas, aunque ocupan espacio y afectan a escrituras."
  },
  {
    "id": 115,
    "topic_num": 18,
    "question": "En C#, que palabra clave declara una clase?",
    "option_a": "route",
    "option_b": "class",
    "option_c": "SELECT",
    "option_d": "branch",
    "correct": "B",
    "explanation": "La palabra clave class declara tipos de referencia definidos por el usuario."
  },
  {
    "id": 116,
    "topic_num": 18,
    "question": "En C#, que instruccion permite iterar sobre una coleccion elemento a elemento?",
    "option_a": "foreach",
    "option_b": "rollback",
    "option_c": "rebase",
    "option_d": "scaffold",
    "correct": "A",
    "explanation": "foreach recorre los elementos de una coleccion o secuencia enumerable."
  },
  {
    "id": 117,
    "topic_num": 19,
    "question": "En MVC, que componente recibe la peticion y selecciona la respuesta adecuada?",
    "option_a": "Controlador",
    "option_b": "Vista",
    "option_c": "Migracion",
    "option_d": "Certificado",
    "correct": "A",
    "explanation": "El controlador procesa la entrada, coordina el modelo y devuelve una vista o resultado."
  },
  {
    "id": 118,
    "topic_num": 19,
    "question": "Que framework CSS se cita en el temario para construir sitios web responsive?",
    "option_a": "PostgreSQL",
    "option_b": "AutoFirma",
    "option_c": "Cl@ve",
    "option_d": "Bootstrap",
    "correct": "D",
    "explanation": "Bootstrap proporciona componentes y rejilla responsive para interfaces web."
  },
  {
    "id": 119,
    "topic_num": 20,
    "question": "En Entity Framework Core, que clase representa la sesion con la base de datos y permite consultar entidades?",
    "option_a": "Controller",
    "option_b": "EditForm",
    "option_c": "Postmaster",
    "option_d": "DbContext",
    "correct": "D",
    "explanation": "DbContext coordina consultas, seguimiento de cambios y persistencia en EF Core."
  },
  {
    "id": 120,
    "topic_num": 20,
    "question": "En EF Core, que mecanismo aplica cambios del modelo al esquema de la base de datos?",
    "option_a": "Stash",
    "option_b": "Valores en cascada",
    "option_c": "Migraciones",
    "option_d": "Claims",
    "correct": "C",
    "explanation": "Las migraciones versionan y aplican cambios de esquema derivados del modelo."
  },
  {
    "id": 121,
    "topic_num": 21,
    "question": "Que tecnologia de .NET permite consultar colecciones con sintaxis integrada en el lenguaje?",
    "option_a": "PKI",
    "option_b": "WCAG",
    "option_c": "LINQ",
    "option_d": "SCSP",
    "correct": "C",
    "explanation": "LINQ integra consultas sobre colecciones, objetos y proveedores de datos."
  },
  {
    "id": 122,
    "topic_num": 21,
    "question": "En LINQ, que tipo de expresion se usa frecuentemente para definir predicados y proyecciones?",
    "option_a": "Sede electronica",
    "option_b": "Expresion lambda",
    "option_c": "Certificado X.509",
    "option_d": "Nivel AA",
    "correct": "B",
    "explanation": "Las lambdas permiten expresar funciones anonimas usadas en Where, Select y otros operadores."
  },
  {
    "id": 123,
    "topic_num": 22,
    "question": "En ASP.NET Core MVC, que proceso enlaza valores de la peticion HTTP con parametros o propiedades del modelo?",
    "option_a": "Revocacion",
    "option_b": "Model binding",
    "option_c": "Rebase",
    "option_d": "Cifrado simetrico",
    "correct": "B",
    "explanation": "El model binding asigna datos de rutas, formularios o query string al modelo de accion."
  },
  {
    "id": 124,
    "topic_num": 22,
    "question": "Que palabra clave de C# permite esperar una tarea asincrona sin bloquear el hilo?",
    "option_a": "await",
    "option_b": "commit",
    "option_c": "select",
    "option_d": "grant",
    "correct": "A",
    "explanation": "await espera la finalizacion de una Task dentro de metodos asincronos."
  },
  {
    "id": 125,
    "topic_num": 23,
    "question": "Que proceso verifica la identidad de un usuario?",
    "option_a": "Autenticacion",
    "option_b": "Autorizacion",
    "option_c": "Indexacion",
    "option_d": "Enrutado",
    "correct": "A",
    "explanation": "La autenticacion responde a quien es el usuario."
  },
  {
    "id": 126,
    "topic_num": 23,
    "question": "Que proceso decide si un usuario autenticado puede acceder a un recurso?",
    "option_a": "Autenticacion",
    "option_b": "Serializacion",
    "option_c": "Compilacion",
    "option_d": "Autorizacion",
    "correct": "D",
    "explanation": "La autorizacion determina permisos sobre acciones o recursos."
  },
  {
    "id": 127,
    "topic_num": 24,
    "question": "Que estilo de servicio web suele exponer recursos mediante verbos HTTP como GET, POST, PUT y DELETE?",
    "option_a": "PGP",
    "option_b": "ROF",
    "option_c": "Stash",
    "option_d": "REST",
    "correct": "D",
    "explanation": "Las API REST usan recursos identificados por URI y operaciones HTTP."
  },
  {
    "id": 128,
    "topic_num": 24,
    "question": "En HTTP, que codigo indica que una peticion se ha completado correctamente?",
    "option_a": "500 Internal Server Error",
    "option_b": "301 Moved Permanently",
    "option_c": "200 OK",
    "option_d": "404 Not Found",
    "correct": "C",
    "explanation": "200 OK indica respuesta satisfactoria para la peticion."
  },
  {
    "id": 129,
    "topic_num": 25,
    "question": "Que estandar permite consultar datos expuestos mediante parametros como $filter y $select?",
    "option_a": "TLS",
    "option_b": "FIRe",
    "option_c": "OData",
    "option_d": "SCSP",
    "correct": "C",
    "explanation": "OData define convenciones para exponer y consultar datos mediante HTTP."
  },
  {
    "id": 130,
    "topic_num": 25,
    "question": "En OData, que parametro selecciona solo determinadas propiedades de una entidad?",
    "option_a": "$top",
    "option_b": "$select",
    "option_c": "$filter",
    "option_d": "$orderby",
    "correct": "B",
    "explanation": "$select limita las propiedades devueltas por el servicio."
  },
  {
    "id": 131,
    "topic_num": 26,
    "question": "Que modelo de alojamiento de Blazor ejecuta componentes en el servidor y actualiza la interfaz mediante SignalR?",
    "option_a": "Web API",
    "option_b": "Blazor Server",
    "option_c": "Blazor WebAssembly",
    "option_d": "MVC clasico",
    "correct": "B",
    "explanation": "Blazor Server mantiene la logica en el servidor y sincroniza la UI con SignalR."
  },
  {
    "id": 132,
    "topic_num": 26,
    "question": "Que modelo de Blazor ejecuta la aplicacion .NET en el navegador del cliente?",
    "option_a": "Blazor WebAssembly",
    "option_b": "Blazor Server",
    "option_c": "Razor Pages",
    "option_d": "Windows Forms",
    "correct": "A",
    "explanation": "Blazor WebAssembly ejecuta codigo .NET en el navegador mediante WebAssembly."
  },
  {
    "id": 133,
    "topic_num": 27,
    "question": "En Blazor, que directiva se usa habitualmente para enlazar un valor de la interfaz con una propiedad?",
    "option_a": "@bind",
    "option_b": "@route",
    "option_c": "@inject",
    "option_d": "@page",
    "correct": "A",
    "explanation": "@bind implementa enlace de datos entre controles y propiedades."
  },
  {
    "id": 134,
    "topic_num": 27,
    "question": "En Blazor, que atributo marca una propiedad para recibir valores desde un componente padre?",
    "option_a": "[Key]",
    "option_b": "[Authorize]",
    "option_c": "[Required]",
    "option_d": "[Parameter]",
    "correct": "D",
    "explanation": "[Parameter] permite pasar datos de un componente padre a uno hijo."
  },
  {
    "id": 135,
    "topic_num": 28,
    "question": "En Blazor, que tipo permite pasar fragmentos de interfaz como contenido reutilizable?",
    "option_a": "DbContext",
    "option_b": "Claim",
    "option_c": "Postmaster",
    "option_d": "RenderFragment",
    "correct": "D",
    "explanation": "RenderFragment representa un fragmento de UI renderizable."
  },
  {
    "id": 136,
    "topic_num": 28,
    "question": "Que tecnica de Blazor limita estilos CSS al componente correspondiente?",
    "option_a": "LINQ",
    "option_b": "OData",
    "option_c": "CSS isolation",
    "option_d": "TLS",
    "correct": "C",
    "explanation": "CSS isolation genera estilos con ambito para evitar efectos globales no deseados."
  },
  {
    "id": 137,
    "topic_num": 29,
    "question": "Que componente de Blazor encapsula un formulario con validacion integrada?",
    "option_a": "Controller",
    "option_b": "Router",
    "option_c": "EditForm",
    "option_d": "DbSet",
    "correct": "C",
    "explanation": "EditForm coordina modelo, envio y validacion en formularios Blazor."
  },
  {
    "id": 138,
    "topic_num": 29,
    "question": "Que atributos de .NET se usan habitualmente para reglas de validacion como Required o StringLength?",
    "option_a": "RenderFragments",
    "option_b": "DataAnnotations",
    "option_c": "Claims",
    "option_d": "Migrations",
    "correct": "B",
    "explanation": "DataAnnotations permite declarar reglas de validacion sobre modelos."
  },
  {
    "id": 139,
    "topic_num": 30,
    "question": "Que patron permite solicitar servicios en constructores o componentes sin crearlos manualmente?",
    "option_a": "Rebase interactivo",
    "option_b": "Inyeccion de dependencias",
    "option_c": "Cifrado simetrico",
    "option_d": "Consulta OData",
    "correct": "B",
    "explanation": "La inyeccion de dependencias desacopla clases de la creacion de sus dependencias."
  },
  {
    "id": 140,
    "topic_num": 30,
    "question": "En .NET, que ciclo de vida crea una instancia nueva del servicio en cada solicitud HTTP?",
    "option_a": "Scoped",
    "option_b": "Singleton",
    "option_c": "Transient",
    "option_d": "Static",
    "correct": "A",
    "explanation": "Scoped mantiene una instancia por ambito, normalmente por solicitud web."
  },
  {
    "id": 141,
    "topic_num": 31,
    "question": "En Blazor, como se denomina la informacion mantenida por un componente durante su renderizado e interaccion?",
    "option_a": "Estado de componente",
    "option_b": "Indice SQL",
    "option_c": "Certificado digital",
    "option_d": "Categoria ENS",
    "correct": "A",
    "explanation": "El estado de componente incluye valores que afectan a su interfaz y comportamiento."
  },
  {
    "id": 142,
    "topic_num": 31,
    "question": "Que tecnica permite conservar datos de usuario aunque se recargue la pagina en el navegador?",
    "option_a": "Rollback",
    "option_b": "Revocacion",
    "option_c": "Normalizacion",
    "option_d": "Persistencia de estado",
    "correct": "D",
    "explanation": "La persistencia de estado puede usar almacenamiento local, sesion u otros mecanismos."
  },
  {
    "id": 143,
    "topic_num": 32,
    "question": "En Blazor, que directiva define la ruta URL de un componente pagina?",
    "option_a": "@bind",
    "option_b": "@code",
    "option_c": "@typeparam",
    "option_d": "@page",
    "correct": "D",
    "explanation": "@page declara la plantilla de ruta que activa el componente como pagina."
  },
  {
    "id": 144,
    "topic_num": 32,
    "question": "Que servicio de Blazor permite navegar por codigo y obtener la URI actual?",
    "option_a": "Postmaster",
    "option_b": "AutoFirma",
    "option_c": "NavigationManager",
    "option_d": "DbContext",
    "correct": "C",
    "explanation": "NavigationManager proporciona metodos y propiedades para navegacion y URI."
  },
  {
    "id": 145,
    "topic_num": 33,
    "question": "Que comando inicializa un repositorio Git local?",
    "option_a": "git merge",
    "option_b": "git clone --bare",
    "option_c": "git init",
    "option_d": "git push",
    "correct": "C",
    "explanation": "git init crea la estructura inicial del repositorio local."
  },
  {
    "id": 146,
    "topic_num": 33,
    "question": "Que comando registra una instantanea de los cambios preparados en Git?",
    "option_a": "git reset --hard",
    "option_b": "git commit",
    "option_c": "git stash",
    "option_d": "git fetch",
    "correct": "B",
    "explanation": "git commit guarda en el historial los cambios del area de preparacion."
  },
  {
    "id": 147,
    "topic_num": 34,
    "question": "Que operacion de Git reaplica commits sobre otra base de historial?",
    "option_a": "tag",
    "option_b": "rebase",
    "option_c": "merge",
    "option_d": "stash",
    "correct": "B",
    "explanation": "Rebase mueve o reaplica commits encima de otra referencia base."
  },
  {
    "id": 148,
    "topic_num": 34,
    "question": "Que comando guarda temporalmente cambios no confirmados para limpiar el arbol de trabajo?",
    "option_a": "git stash",
    "option_b": "git branch",
    "option_c": "git blame",
    "option_d": "git remote",
    "correct": "A",
    "explanation": "git stash aparta cambios locales para recuperarlos posteriormente."
  },
  {
    "id": 149,
    "topic_num": 35,
    "question": "Que comando envia commits locales a un repositorio remoto?",
    "option_a": "git push",
    "option_b": "git pull",
    "option_c": "git fetch",
    "option_d": "git status",
    "correct": "A",
    "explanation": "git push publica commits locales en el remoto configurado."
  },
  {
    "id": 150,
    "topic_num": 35,
    "question": "Que practica propone integrar cambios mediante revision antes de fusionarlos en la rama principal?",
    "option_a": "Rollback",
    "option_b": "Certificado digital",
    "option_c": "Model binding",
    "option_d": "Pull request",
    "correct": "D",
    "explanation": "Una pull request facilita revision, debate y validaciones antes de integrar cambios."
  },
  {
    "id": 151,
    "topic_num": 36,
    "question": "En administracion electronica, que punto permite a la ciudadania acceder electronicamente a servicios y tramites?",
    "option_a": "Indice B-tree",
    "option_b": "RenderFragment",
    "option_c": "Repositorio bare",
    "option_d": "Sede electronica",
    "correct": "D",
    "explanation": "La sede electronica es la direccion electronica disponible para relaciones con la Administracion."
  },
  {
    "id": 152,
    "topic_num": 36,
    "question": "Que concepto agrupa documentos, actuaciones y metadatos de un procedimiento administrativo electronico?",
    "option_a": "Pull request",
    "option_b": "Claim",
    "option_c": "Expediente electronico",
    "option_d": "Cluster PostgreSQL",
    "correct": "C",
    "explanation": "El expediente electronico reune documentos y actuaciones del procedimiento."
  },
  {
    "id": 153,
    "topic_num": 37,
    "question": "En SedipuAlba, que modulo se asocia a la gestion de expedientes?",
    "option_a": "Segra",
    "option_b": "Secoin",
    "option_c": "Segex",
    "option_d": "Sefycu",
    "correct": "C",
    "explanation": "Segex es el modulo de gestion de expedientes de la plataforma."
  },
  {
    "id": 154,
    "topic_num": 37,
    "question": "En SedipuAlba, que modulo se asocia a la firma y custodia de documentos?",
    "option_a": "Seres",
    "option_b": "Sefycu",
    "option_c": "Segex",
    "option_d": "Segra",
    "correct": "B",
    "explanation": "Sefycu se relaciona con firma y custodia documental dentro de la plataforma."
  },
  {
    "id": 155,
    "topic_num": 38,
    "question": "Que red conecta administraciones publicas espanolas para intercambio seguro de informacion?",
    "option_a": "Red NAT privada",
    "option_b": "Red SARA",
    "option_c": "Red TOR",
    "option_d": "Red CDN",
    "correct": "B",
    "explanation": "La Red SARA facilita comunicaciones seguras entre Administraciones Publicas."
  },
  {
    "id": 156,
    "topic_num": 38,
    "question": "Que especificaciones permiten consultar datos de otras administraciones evitando pedir documentos al ciudadano?",
    "option_a": "SCSP",
    "option_b": "OData",
    "option_c": "PGP",
    "option_d": "WCAG",
    "correct": "A",
    "explanation": "SCSP estandariza servicios de verificacion y consulta de datos entre administraciones."
  },
  {
    "id": 157,
    "topic_num": 39,
    "question": "Que sistema comun permite identificacion, autenticacion y firma para ciudadanos ante las AAPP?",
    "option_a": "Cl@ve",
    "option_b": "Bootstrap",
    "option_c": "pg_dump",
    "option_d": "LINQ",
    "correct": "A",
    "explanation": "Cl@ve es una plataforma comun de identificacion y autenticacion del sector publico."
  },
  {
    "id": 158,
    "topic_num": 39,
    "question": "Que servicio facilita la firma electronica centralizada en el sector publico?",
    "option_a": "SIR",
    "option_b": "PID",
    "option_c": "WCAG",
    "option_d": "FIRe",
    "correct": "D",
    "explanation": "FIRe facilita integracion de servicios de firma electronica en aplicaciones publicas."
  },
  {
    "id": 159,
    "topic_num": 40,
    "question": "Que pautas internacionales sirven de referencia para accesibilidad del contenido web?",
    "option_a": "ACID",
    "option_b": "PKI",
    "option_c": "LINQ",
    "option_d": "WCAG",
    "correct": "D",
    "explanation": "Las WCAG establecen criterios de accesibilidad para contenido web."
  },
  {
    "id": 160,
    "topic_num": 40,
    "question": "Que nivel de conformidad WCAG es el exigido habitualmente por la normativa europea para el sector publico?",
    "option_a": "AAA",
    "option_b": "Beta",
    "option_c": "AA",
    "option_d": "A",
    "correct": "C",
    "explanation": "La normativa suele tomar como referencia WCAG nivel AA."
  }
]
